build: 
  image: balser/ruby-buildbox:2.3
  environment:
    - AWS_DEFAULT_REGION=$$NP_AWS_DEFAULT_REGION
    - AWS_ACCESS_KEY_ID=$$NP_AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$$NP_AWS_SECRET_ACCESS_KEY
  commands:
    - ./build_gem.sh
  when:
    branch: master
    event: push